Change interface for detached content
laurencelundblade/t_cose pull request #144
Opened 2022-12-31 15:34 UTC by kentakayama

Relate to #122 , changing interfaces and roles of 
- `t_cose_sign1_encode_parameters`
- `t_cose_sign1_encode_signature`
- `t_cose_sign_encode_start`
- `t_cose_sign_encode_finish`
- `t_cose_mac_encode_parameters`
- `t_cose_mac_encode_tag`

4 conditional branches are removed in total.
Two-step signing (computing mac) need to call `QCBOREncode_BstrWrap` and `QCBOREncode_CloseBstrWrap2` respectively, but the performance and code size would be improved.

2023-03-01 16:49 UTC, laurencelundblade requested changes
I'd like to merge this. I agree that the interface change is good. Thank you for the suggestion and PR.

There are two issues:
 - The merge conflicts
- Backwards compatibility with t_cose_sign1. That interface is provided for backwards compatibility, so it can't change. There needs to be some code to adapt it to the new interface in t_cose_sign.

Thx!

LL

2023-03-01 16:49 UTC, laurencelundblade commented on inc/t_cose/t_cose_sign1_sign.h
> +                              struct q_useful_buf_c         payload,
This interface can't be changed. Backwards compatibility needs to be provided here.

2023-03-01 16:49 UTC, laurencelundblade commented on examples/t_cose_basic_example_ossl.c
> +    QCBOREncode_BstrWrap(&cbor_encode);
The examples where rearranged, so this file doesn't exist any more, but you can find the same example in signing_examples.c. The same code is use for both PSA and Mbed TLS so you only need one change.

2023-03-29 09:29 UTC, kentakayama commented
I've done.
The interface of `t_cose_sign1_encode_parameters` is not changed, but **the role was changed**.

# Before
## On not detached content mode
```
COSE_Sign1 = [
    Headers,
    payload : <<
```

## On detached content mode
```
COSE_Sign1 = [
    Headers
```

# After
## On both not detached content mode and detached content mode
```
COSE_Sign1 = [
    Headers
```

That's why the interfaces are simplified and `QCBOREncode_BstrWrap()` are needed in the caller.
If you don't want such changes, then [this commit](https://github.com/laurencelundblade/t_cose/pull/144/commits/df64f2b23c6ecf532843e9e2c314d9ecbca3fcf1) is enough.

2023-03-29 09:33 UTC, kentakayama commented
And `t_cose_sign1_encode_signature2` was added to avoid changing `t_cose_sign1_encode_signature` .
https://github.com/laurencelundblade/t_cose/pull/144/files#diff-5b4b142e0ea21623123247a5a8d7cb7e5cdb5503c389c93881fd05f3195eba8bR601-R610

2023-03-30 08:15 UTC, kentakayama commented
@laurencelundblade 
I kept the interface and role of `t_cose_sign1_encode_parameter` and  `t_cose_sign1_encode_signature` .
The test codes that use those functions has not been changed.

2023-03-31 03:19 UTC, merged