COSE Encrypt: Redesign of Recipient Structure
laurencelundblade/t_cose pull request #75
Opened 2022-06-13 09:40 UTC by hannestschofenig

This PR contains COSE encryption functionality and offers key distribution via HPKE and AES Key Wrap. 

Note: A description of HPKE in COSE can be found in https://datatracker.ietf.org/doc/html/draft-ietf-cose-hpke and the used HPKE library is available at https://github.com/hannestschofenig/mbedtls/tree/hpke.

Important: This is work in  progress. Expect changes to the API and to the internals of the implementation. 

Change-Id: I190f58a82eb4a883e04f1a5cf17cd40bd27ea9ff

2022-09-11 22:07 UTC, laurencelundblade requested changes
The requested changes here are focused just on what is needed to merge this PR. They are mostly about dependency and common files like Makefiles that are subject to a lot of churn from other inbound PRs.

Once encrypt is merged, then there will be other things to work on in the design and implementation, but they can be handled in smaller and easier chunks.

2022-09-11 22:07 UTC, laurencelundblade commented on src/t_cose_aes_kw.c
> + *
Rename to t_cose_recipient_enc_kw.{ch}

2022-09-11 22:07 UTC, laurencelundblade commented on inc/t_cose/t_cose_hpke.h
> + * t_cose_hpke.h
Rename to t_cose_recipient_enc_hpke.{ch}

2022-10-02 11:27 UTC, hannestschofenig commented on crypto_adapters/t_cose_psa_crypto.c
> +#include <mbedtls/nist_kw.h>
Unfortunately, there are no PSA APIs for AES-KW and for HPKE. However, the implementation of AES-KW and HPKE uses PSA APIs internally.

2022-11-06 10:01 UTC, hannestschofenig commented
To address the comments by Laurence and the changes in the t_cose codebase since the submission of this PR I created a new PR, which can be found here: #115

2022-11-11 10:18 UTC, laurencelundblade commented
replaced by https://github.com/laurencelundblade/t_cose/pull/116

2022-11-11 10:18 UTC, closed without merging